### PR TITLE
modernization

### PR DESCRIPTION
**Pull request by ktarplee**
This pull request cherry picked the commit from #37 but went further.  The deprecated sum{} have been converted to sum().  Other functions used from JuMP have also been updated.  As part of this work an issue was submitted and closed to allow the BendersBridge to cycle (not work yet) on an LP, see JuliaOpt/MathProgBase.jl#146.

I also took the liberty of adding the scaffolding for unit testing but I am new to Julia so hopefully it is a step in the right direction.

### CODE REVIEW

**Comment by ktarplee** [comment]
I should have mentioned that this also fixes a bug in getprobability().

**Comment by blegat** [comment]
What do you mean by "cycle on an LP" ?

**Comment by ktarplee** [comment]
The case I tried is when all the StructuredBlocks are linear programs and the solver is a linear solver such as Clp (see farmer.jl).  It currently cycles (runs to completion) but it give the wrong answer.

**Comment by joehuchette** [comment]
Thanks!

**Pull request merged**
