### PR TITLE
Export Benders #47

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Comment by ktarplee** [comment]
Should the public functions from BendersBridge.jl instead be exported by StructJuMP.jl?  Then those if statements could be removed (and the include replaced with "using StructJuMP").  See #47

**Comment by blegat** [comment]
@ktarplee Agreed, I have update the PR.

**Comment by joehuchette** [comment]
Looks fine with me, good to merge once travis is passing.

**Comment by blegat** [comment]
The Travis failure is only on Mac OS nightly and is unrelated to this PR

**Pull request merged**
